version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dolar_predictor_api
    ports:
      - "8000:8000"
    environment:
      - LOG_LEVEL=info
      - PYTHONUNBUFFERED=1
    volumes:
      # Montar modelos (para hot-reload sin rebuild)
      - ./models:/app/models:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/health', timeout=5)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - dolar_network

networks:
  dolar_network:
    driver: bridge
